"use client"

import { useMemo } from "react"
import { useWalletData as useWalletDataContext } from "@/contexts/wallet-data-context"

export function useWalletData() {
  const wallet = useWalletDataContext()

  return useMemo(
    () => ({
      userProfile: wallet.userProfile,
      transactions: wallet.transactions,
      budgets: wallet.budgets,
      goals: wallet.goals,
      categories: wallet.categories,
      emergencyFund: wallet.emergencyFund,
      balance: wallet.balance,
      isFirstTime: wallet.isFirstTime,
      showOnboarding: wallet.showOnboarding,
      isAuthenticated: wallet.isAuthenticated,
      isLoaded: wallet.isLoaded,
      balanceChange: wallet.balanceChange,
      setShowOnboarding: wallet.setShowOnboarding,
      handleOnboardingComplete: wallet.handleOnboardingComplete,
      addTransaction: wallet.addTransaction,
      updateUserProfile: wallet.updateUserProfile,
      addBudget: wallet.addBudget,
      updateBudget: wallet.updateBudget,
      deleteBudget: wallet.deleteBudget,
      addGoal: wallet.addGoal,
      updateGoal: wallet.updateGoal,
      deleteGoal: wallet.deleteGoal,
      useGoalForInvestment: wallet.useGoalForInvestment,
      deleteTransaction: wallet.deleteTransaction,
      updateTransaction: wallet.updateTransaction,
      addToEmergencyFund: wallet.addToEmergencyFund,
      updateGoalContribution: wallet.updateGoalContribution,
      transferToGoal: wallet.transferToGoal,
      spendFromGoal: wallet.spendFromGoal,
      addFromGoal: wallet.addFromGoal,
      refreshData: wallet.refreshData,
      clearAllData: wallet.clearAllData,
      exportData: wallet.exportData,
      importData: wallet.importData,
      calculateTimeEquivalent: wallet.calculateTimeEquivalent,
      addCategory: wallet.addCategory,
      updateCategory: wallet.updateCategory,
      deleteCategory: wallet.deleteCategory,
      updateCategoryStats: wallet.updateCategoryStats,
      settings: wallet.settings,
    }),
    [
      wallet.userProfile,
      wallet.transactions,
      wallet.budgets,
      wallet.goals,
      wallet.categories,
      wallet.emergencyFund,
      wallet.balance,
      wallet.isFirstTime,
      wallet.showOnboarding,
      wallet.isAuthenticated,
      wallet.isLoaded,
      wallet.balanceChange,
      wallet.setShowOnboarding,
      wallet.handleOnboardingComplete,
      wallet.addTransaction,
      wallet.updateUserProfile,
      wallet.addBudget,
      wallet.updateBudget,
      wallet.deleteBudget,
      wallet.addGoal,
      wallet.updateGoal,
      wallet.deleteGoal,
      wallet.useGoalForInvestment,
      wallet.deleteTransaction,
      wallet.updateTransaction,
      wallet.addToEmergencyFund,
      wallet.updateGoalContribution,
      wallet.transferToGoal,
      wallet.spendFromGoal,
      wallet.addFromGoal,
      wallet.refreshData,
      wallet.clearAllData,
      wallet.exportData,
      wallet.importData,
      wallet.calculateTimeEquivalent,
      wallet.addCategory,
      wallet.updateCategory,
      wallet.deleteCategory,
      wallet.updateCategoryStats,
      wallet.settings,
    ],
  )
}
